import type { Metadata } from "next";
import "./globals.css";
import BottomNav from "@/_components/bottom-nav";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-BR">
      <body className="bg-blue-950 min-h-screen">
        <main>{children}</main>
        <BottomNav />
      </body>
    </html>
  );
}
